recipe_hash = {

	old_fashioned: [:whiskey],
	margarita: [:tequila, :cointreau],
	negroni: [:gin, :campari, :sweet_vermouth],
	french_75: [:champagne, :gin],
	manhattan: [:whiskey, :vermouth],
	gin_and_tonic: [:gin],
	screwdriver: [:vodka],
	martini: [:gin, :dry_vermouth],
	cosmopolitan: [:cointreau, :vodka_citron],
	stinger: [:cognac, :creme_de_menthe],
	americano: [:campari, :red_vermouth],
	white_russian: [:coffee_liquer, :vodka],
	daiquiri: [:rum],
	bloody_mary: [:vodka],
	whiskey_sour: [:whiskey],
	long_island_ice_tea: [:tequila, :vodka, :triple_sec, :gin, :white_rum],
	fizz: [:gin],
	mai_tai: [:white_rum, :dark_rum, :orange_curacao],
	mint_julep: [:whiskey],
	pina_colada: [:white_rum],
	sidecar: [:cognac, :triple_sec],
	moscow_mule: [:vodka],
	tequila_sunrise: [:tequila],
	tom_collins: [:gin],
	gimlet: [:gin],
	sex_on_the_beach: [:vodka, :peach_schnapps],
	bellini: [:prosecco],
	dark_n_stormy: [:dark_rum],
	cuba_libre: [:white_rum],
	black_russian: [:coffee_liquer, :vodka],
	sea_breeze: [:vodka],


}
